version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    
  mosquitto:
    volumes:
      - ./mosquitto.dev.conf:/mosquitto/config/mosquitto.conf 